[package]
name = "deno_audio"
version = "0.3.1"
authors = ["Divy Srivastava <dj.srivastava23@gmail.com>", "Robert Kunze"]
edition = "2018"
publish = false

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
rodio = "0.17.0"
bstr = "0.2"
